-- Drop tables if they exist
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE applications CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE customers CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- Create customers table
CREATE TABLE customers (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    password VARCHAR2(255) NOT NULL,
    address VARCHAR2(255),
    phone VARCHAR2(20),
    gender VARCHAR2(10)
);

-- Create applications table
CREATE TABLE applications (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    dob DATE,
    passport_number VARCHAR2(20),
    status VARCHAR2(50) DEFAULT 'Pending',
    FOREIGN KEY (customer_id) REFERENCES customers(id)
);

-- Sample data (optional)
INSERT INTO customers (username, email, password, address, phone, gender)
VALUES ('john_doe', 'john@example.com', 'hashed_password', '123 Main St', '1234567890', 'Male');

INSERT INTO customers (username, email, password, address, phone, gender)
VALUES ('jane_smith', 'jane@example.com', 'hashed_password', '456 Oak Ave', '0987654321', 'Female');

INSERT INTO applications (customer_id, first_name, last_name, dob, passport_number, status)
VALUES (1, 'John', 'Doe', TO_DATE('1990-05-12', 'YYYY-MM-DD'), 'P1234567', 'Approved');

INSERT INTO applications (customer_id, first_name, last_name, dob, passport_number, status)
VALUES (2, 'Jane', 'Smith', TO_DATE('1992-08-25', 'YYYY-MM-DD'), 'P7654321', 'Pending');

COMMIT;




SELECT owner, table_name FROM all_tables WHERE table_name = 'APPLICATIONS';

